<a href="https://colab.research.google.com/github/Nomnomers/DataAnalyst_freecodecamp/blob/main/Numpy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Basic Numpy Arrays**

In [2]:
import sys
import numpy as np

In [3]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1, 2, 3, 4])

In [5]:
b = np.array([0, .5, 1, 1.5, 2])

In [6]:
a[0], a[1]

(1, 2)

In [7]:
a[0:]

array([1, 2, 3, 4])

In [8]:
a[1:3]

array([2, 3])

In [10]:
a[1: -1]

array([2, 3])

In [11]:
a[::2]

array([1, 3])

In [12]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [13]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [14]:
b[[0, 2, -1]]

array([0., 1., 2.])

**Array Types**

In [15]:
a

array([1, 2, 3, 4])

In [16]:
a.dtype

dtype('int64')

In [17]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [18]:
b.dtype

dtype('float64')

In [19]:
np.array([1, 2, 3, 4], dtype = np.float)

array([1., 2., 3., 4.])

In [20]:
np.array([1, 2, 3, 4], dtype = np.int8)

array([1, 2, 3, 4], dtype=int8)

In [21]:
c = np.array(['a', 'b', 'c'])

In [22]:
c.dtype

dtype('<U1')

In [23]:
d = np.array([{'a' : 1}, sys])

In [24]:
d.dtype

dtype('O')

**Dimensions and Shapes**

In [26]:
A = np.array(
      [
       [1, 2, 3],
       [4, 5, 6]
      ]
  )

In [27]:
A.shape

(2, 3)

In [28]:
A.ndim

2

In [29]:
A.size

6

In [33]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [34]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [35]:
B.shape

(2, 2, 3)

In [36]:
B.ndim

3

In [37]:
B.size

12

In [39]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  import sys


In [40]:
C.dtype

dtype('O')

In [41]:
C.shape

(2,)

In [42]:
C.size

2

In [43]:
type(C[0])

list

**Indexing and Slicing**

In [45]:
A = np.array([
           #. 0. 1. 2
              [1, 2, 3], # 0
              [4, 5, 6], # 1
              [7, 8, 9], # 2
])

In [46]:
A[1]

array([4, 5, 6])

In [47]:
A[1][0]

4

In [48]:
# A[d1, d2, d3, d4]

In [49]:
A[1, 0]

4

In [50]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [52]:
A[:2, 2:]

array([[3],
       [6]])

In [53]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
A[1] = np.array([10, 10, 10])

In [55]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [57]:
A[2] = 99

In [58]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

**Summary Statistics**

In [59]:
a = np.array([1, 2, 3, 4])

In [60]:
a.sum()

10

In [61]:
a.mean()

2.5

In [62]:
a.std()

1.118033988749895

In [63]:
a.var()

1.25

In [64]:
A = np.array([
              [1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]
])

In [65]:
A.sum()

45

In [66]:
A.mean()

5.0

In [67]:
A.std()

2.581988897471611

In [68]:
A.sum(axis = 0)

array([12, 15, 18])

In [69]:
A.sum(axis = 1)

array([ 6, 15, 24])

In [70]:
A.mean(axis = 0)

array([4., 5., 6.])

In [71]:
A.mean(axis = 1)

array([2., 5., 8.])

In [72]:
A.std(axis = 0)

array([2.44948974, 2.44948974, 2.44948974])

In [73]:
A.std(axis = 1)

array([0.81649658, 0.81649658, 0.81649658])

**Broadcast and Vector Operations**

In [75]:
a = np.arange(4)

In [76]:
a

array([0, 1, 2, 3])

In [77]:
a + 10

array([10, 11, 12, 13])

In [78]:
a * 10

array([ 0, 10, 20, 30])

In [80]:
a

array([0, 1, 2, 3])

In [81]:
a += 10

In [82]:
a

array([10, 11, 12, 13])

In [83]:
a += 100

In [84]:
a

array([110, 111, 112, 113])

In [85]:
l = [0, 1, 2, 3]

In [86]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [87]:
a = np.arange(4)

In [88]:
a

array([0, 1, 2, 3])

In [89]:
b = np.array([10, 10, 10, 10])

In [90]:
a + b

array([10, 11, 12, 13])

In [91]:
a * b

array([ 0, 10, 20, 30])

**Boolean Arrays**

In [92]:
a = np.arange(4)

In [93]:
a

array([0, 1, 2, 3])

In [94]:
a[[0, -1]]

array([0, 3])

In [95]:
a[[True, False, False, True]]

array([0, 3])

In [96]:
a >= 2

array([False, False,  True,  True])

In [97]:
a.mean()

1.5

In [98]:
a[a > a.mean()]

array([2, 3])

In [99]:
a[~(a > a.mean())]

array([0, 1])

In [100]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [101]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [103]:
A = np.random.randint(100, size = (3, 3))

In [104]:
A  

array([[47, 22, 21],
       [46, 86, 11],
       [54, 95, 24]])

In [105]:
A[np.array([
            [True, False, True],
            [False, True, True],
            [True, False, True]
])]

array([47, 21, 86, 11, 54, 24])

In [106]:
A > 30

array([[ True, False, False],
       [ True,  True, False],
       [ True,  True, False]])

In [107]:
A[A > 30]

array([47, 46, 86, 54, 95])

**Linear Algebra**

In [108]:
A = np.array([
              [1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]
])

In [109]:
B = np.array([
              [6, 5],
              [4, 3], 
              [2, 1]
])

In [110]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [111]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [112]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [113]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [114]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

**Objects Size in Memory**

In [115]:
sys.getsizeof(1)

28

In [117]:
sys.getsizeof(10 ** 100)

72

In [118]:
np.dtype(int).itemsize

8

In [119]:
np.dtype(float).itemsize

8

In [120]:
sys.getsizeof([1])

80

In [121]:
np.array([1]).nbytes

8

In [122]:
l = list(range(1000))

In [125]:
a = np.arange(1000)

In [126]:
%time np.sum(a ** 2)

CPU times: user 1.21 ms, sys: 12 µs, total: 1.22 ms
Wall time: 1.34 ms


332833500

In [127]:
%time sum([x ** 2 for x in l])

CPU times: user 1.2 ms, sys: 0 ns, total: 1.2 ms
Wall time: 1.74 ms


332833500

**Numpy Functions**

In [128]:
np.random.random(size = 2)

array([0.82888648, 0.06041759])

In [129]:
np.random.normal(size = 2)

array([-0.39290159,  1.05785132])

In [130]:
np.random.rand(2, 4)

array([[0.66511664, 0.27828021, 0.29844383, 0.45005952],
       [0.45610922, 0.98621391, 0.67763656, 0.17814307]])

In [131]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [132]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [134]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [135]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [136]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [137]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [138]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [139]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [141]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [142]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [143]:
np.zeros((3, 3), dtype = np.int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [144]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [146]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [147]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [149]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [150]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [151]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [152]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [153]:
np.eye(8, 4, k = 1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [154]:
np.eye(8, 4, k = 3)

array([[0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [155]:
"Hello World"[6]

'W'